update: set path for config folder from CLI

diff --git a/bin/up b/bin/up
--- a/bin/up
+++ b/bin/up
@@ -15,8 +15,41 @@ if [[ ! -d "$TOOLKIT_ROOT/bin" ]] || [[ ! -d "$TOOLKIT_ROOT/config" ]]; then
   echo "ERROR: could not find root of overleaf-toolkit project (inferred project root as '$TOOLKIT_ROOT')"
   exit 1
 fi
+CONFIG_DIR=""
 
-source "$TOOLKIT_ROOT/lib/shared-functions.sh"
+#### Parse argument folder ####
+function parse_args(){
+  while getopts "c:" opt; do
+    case $opt in
+      c)
+        CONFIG_DIR="$OPTARG"
+        ;;
+      *)
+        echo "Usage: $0 -c <config_folder>"
+        exit 1
+        ;;
+    esac
+    echo OPT:$OPTARG
+  done
+
+  # Check if config dir is provided
+  if [ -z "$CONFIG_DIR" ]; then
+    echo "Error: Config folder not specified. Use -c <path>"
+    exit 1
+  fi
+}
+
+parse_args "$@"
+export CONFIG_DIR; source "$TOOLKIT_ROOT/lib/shared-functions.sh"
+
+# Validate directory exists
+function check_config() {
+  if [[ ! -f "$CONFIG_DIR/overleaf.rc" ]] \
+      || [[ ! -f "$CONFIG_DIR/variables.env" ]]; then
+    echo "Config files not found! exiting"
+    exit 1
+  fi
+}
 
 function usage() {
   echo "Usage: bin/up [FLAGS...]"
@@ -25,14 +58,6 @@ function usage() {
   echo ""
   echo "This program will pass any extra flags to docker compose,"
   echo "for example: 'bin/up -d' will run in detached mode"
-}
-
-function check_config() {
-  if [[ ! -f "$TOOLKIT_ROOT/config/overleaf.rc" ]] \
-      || [[ ! -f "$TOOLKIT_ROOT/config/variables.env" ]]; then
-    echo "Config files not found! exiting"
-    exit 1
-  fi
 }
 
 function initiate_mongo_replica_set() {
@@ -54,7 +79,7 @@ function pull_sandboxed_compiles() {
   local images=$(read_variable "ALL_TEX_LIVE_DOCKER_IMAGES")
   if [[ -z "$images" ]]; then
     echo
-    echo "Please configure ALL_TEX_LIVE_DOCKER_IMAGES in $TOOLKIT_ROOT/config/variables.env"
+    echo "Please configure ALL_TEX_LIVE_DOCKER_IMAGES in $CONFIG_DIR/variables.env"
     echo
     echo "You can read more about configuring Sandboxed Compiles in our documentation:"
     echo "  https://github.com/overleaf/overleaf/wiki/Server-Pro:-sandboxed-compiles#changing-the-texlive-image"
@@ -107,7 +132,7 @@ function __main__() {
   fi
 
   notify_about_not_using_detach_mode "$@"
-  exec "$TOOLKIT_ROOT/bin/docker-compose" up "$@"
+  exec "$TOOLKIT_ROOT/bin/docker-compose" up "${DOCKER_COMPOSE_UP_OPTIONS}"
 }
 
 __main__ "$@"
